version: '3.8'

services:
  mongodb:
    image: mongo:5.0.6  # ถ้ามี Dockerfile.mongo เปลี่ยนเป็น build: .
    container_name: mongodb
    ports:
      - "27017:27017"  # Map port 27017 on host to container
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local