version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: purchase-order-api
    ports:
      - "8080:8080"
    environment:
      - API_HOST=10.10.5:8080  # สำหรับ production
      # - API_HOST=localhost:8080  # สำหรับ local development
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 