basePath: /
definitions:
  models.PurchaseOrder:
    properties:
      customer:
        type: string
      delivery_date:
        type: string
      distribution:
        type: string
      job_id_no:
        type: string
      ordered:
        type: integer
      payment_term:
        type: string
      po:
        type: string
      po_date:
        type: string
      pr:
        type: string
      pr_date:
        type: string
      product_code:
        type: string
      product_description:
        type: string
      project_manager:
        type: string
      received:
        type: integer
      remain:
        type: integer
      request_date:
        type: string
      sales_team:
        type: string
      status:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API for processing Excel order data
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Excel Order API
  version: "1.0"
paths:
  /purchaseorders:
    get:
      description: Retrieves purchase order data from an Excel file located on a fixed
        network share path
      parameters:
      - description: Filter orders by Job ID No
        in: query
        name: job_id_no
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.PurchaseOrder'
              type: array
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Import purchase orders from Excel file on network share
      tags:
      - purchaseorders
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
